name: mr_garage
description: "Mr.Garage merupakan aplikasi layanan servis bengkel untuk kendaraan anda serta pembelanjaan mengenai spare part kendaraan anda"

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

#------------------- Packages -------------------#
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  hexcolor: ^3.0.1
  google_fonts: ^6.2.1
  flutter_feather_icons: ^2.0.0+1
  image_picker: ^1.0.7
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  awesome_notifications: ^0.8.2
  awesome_snackbar_content: ^0.1.3
  flutter_svg: ^2.0.10+1
  dropdown_button2: ^2.3.9
  carousel_slider: ^4.2.1
  material_symbols_icons: ^4.2719.3
  permission_handler: ^11.3.1
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.4
  image_cropper: ^6.0.0
  firebase_messaging: ^14.9.2
  email_validator: ^2.1.17
  loading_animation_widget: ^1.2.1
  url_launcher: ^6.2.6
  google_sign_in: ^6.2.1
  path: ^1.9.0
  intl: ^0.19.0
  connectivity_plus: ^6.0.3
  flutter_rating_bar: ^4.0.1
#------------------- Packages Ends -------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  #------------------- Local Assets -------------------#
  assets:
    - assets/
    - assets/animation/
    - assets/img/
    - assets/img/logo/
    - assets/img/banner/
    - assets/img/vehicle/
    - assets/img/product/
    - assets/img/icon/
    - assets/img/illustrator/
    - assets/img/bengkel/
  #------------------- Local Assets End -------------------#

  #------------------- Local Fonts -------------------#
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
  #------------------- Local Fonts End -------------------#

#------------------- Flutter Native Splash -------------------#
flutter_native_splash:
  color: "#007EA7"

  android_12:
    color: "#007EA7"

  android: true
  ios: true
  web: false
#------------------- Flutter Native Splash Ends -------------------#

#------------------- Flutter Launcher Icons -------------------#
flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/img/logo/logo-mrgarage-icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/img/logo/logo-mrgarage-icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
#------------------- Flutter Launcher Icons Ends -------------------#
